openai:
  key: ${OPEN_AI_KEY}
  chat-url: https://api.openai.com

weather:
  key: ${WEATHER_KEY}
  url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
  data_type: JSON

naver:
  search:
    url: https://openapi.naver.com
    client-id: ${NAVER_SEARCH_CLIENT_ID}
    client-secret: ${NAVER_SEARCH_CLIENT_SECRET}
  address:
    url: https://naveropenapi.apigw.ntruss.com/map-reversegeocode
    client-id: ${NAVER_ADDRESS_CLIENT_ID}
    client-secret: ${NAVER_ADDRESS_CLIENT_SECRET}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #    hibernate:
  #      ddl-auto: create

logging:
  level:
    com.example.recommendation.infra.feign: DEBUG